snowflake:
  account: paccar
  role: DAF_58118_CONNECT_R
  warehouse: DAF_EHV_58_118_XSMALL_WH #Other sizes available. Tony recommended starting small and working up. Sizing is based on computing power required.
  sa:
    username: SNOWFLAKE_USER_DAF_LEY # put env variable name of service account
    password: SNOWFLAKE_PASSWORD_DAF_LEY # put env variable for service account password (these will be in your .bashrc or you can use a .env file and loadenv())
  sso:
    username: # kingsley.nwosu@leyland-trucks.co.uk
  database: DAF_DB
  schema: DAF_CONNECT
